// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParkingBuildingManagementSystem_BE.Data;

#nullable disable

namespace ParkingBuildingManagementSystem_BE.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260528053114_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("Vietnamese_CI_AS")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FloorVehicleType", b =>
                {
                    b.Property<int>("FloorId")
                        .HasColumnType("int")
                        .HasColumnName("floor_id");

                    b.Property<int>("VehicleTypeId")
                        .HasColumnType("int")
                        .HasColumnName("vehicle_type_id");

                    b.HasKey("FloorId", "VehicleTypeId")
                        .HasName("pk_floor_vehicle_types");

                    b.HasIndex("VehicleTypeId");

                    b.ToTable("floor_vehicle_types", (string)null);
                });

            modelBuilder.Entity("ParkingBuildingManagementSystem_BE.Models.ActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("ip_address");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("new_value");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("old_value");

                    b.Property<int?>("TargetId")
                        .HasColumnType("int")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetTable")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("target_table");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK__activity__3213E83F003B2CE4");

                    b.HasIndex(new[] { "UserId", "CreatedAt" }, "idx_logs_user_date")
                        .IsDescending(false, true);

                    b.ToTable("activity_logs", (string)null);
                });

            modelBuilder.Entity("ParkingBuildingManagementSystem_BE.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CancelReason")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("cancel_reason");

                    b.Property<DateTime>("CheckinDeadline")
                        .HasColumnType("datetime2")
                        .HasColumnName("checkin_deadline");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal>("DepositPaid")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("deposit_paid");

                    b.Property<int>("FloorId")
                        .HasColumnType("int")
                        .HasColumnName("floor_id");

                    b.Property<string>("QrCode")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("qr_code");

                    b.Property<DateTime>("ScheduledCheckin")
                        .HasColumnType("datetime2")
                        .HasColumnName("scheduled_checkin");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("pending_payment")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int")
                        .HasColumnName("vehicle_id");

                    b.Property<int>("VehicleTypeId")
                        .HasColumnType("int")
                        .HasColumnName("vehicle_type_id");

                    b.HasKey("Id")
                        .HasName("PK__bookings__3213E83FEBE65F1B");

                    b.HasIndex("VehicleId");

                    b.HasIndex("VehicleTypeId");

                    b.HasIndex(new[] { "QrCode" }, "UQ__bookings__E2FB88893F98E923")
                        .IsUnique()
                        .HasFilter("[qr_code] IS NOT NULL");

                    b.HasIndex(new[] { "CheckinDeadline", "Status" }, "idx_bookings_expiry")
                        .HasFilter("([status]='confirmed')");

                    b.HasIndex(new[] { "FloorId", "Status", "CheckinDeadline" }, "idx_bookings_floor_confirmed")
                        .HasFilter("([status]='confirmed')");

                    b.HasIndex(new[] { "UserId", "Status", "CreatedAt" }, "idx_bookings_user_status")
                        .IsDescending(false, false, true);

                    b.ToTable("bookings", (string)null);
                });

            modelBuilder.Entity("ParkingBuildingManagementSystem_BE.Models.Floor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("description");

                    b.Property<int>("FloorNumber")
                        .HasColumnType("int")
                        .HasColumnName("floor_number");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.Property<int>("TotalSlots")
                        .HasColumnType("int")
                        .HasColumnName("total_slots");

                    b.HasKey("Id")
                        .HasName("PK__floors__3213E83F7A91A04E");

                    b.HasIndex(new[] { "FloorNumber" }, "UQ__floors__4AE77A4B24253A70")
                        .IsUnique();

                    b.ToTable("floors", (string)null);
                });

            modelBuilder.Entity("ParkingBuildingManagementSystem_BE.Models.Incident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int?>("HandledBy")
                        .HasColumnType("int")
                        .HasColumnName("handled_by");

                    b.Property<string>("IncidentType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("incident_type");

                    b.Property<int>("ReportedBy")
                        .HasColumnType("int")
                        .HasColumnName("reported_by");

                    b.Property<string>("Resolution")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("resolution");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("resolved_at");

                    b.Property<int?>("SessionId")
                        .HasColumnType("int")
                        .HasColumnName("session_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("open")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("PK__incident__3213E83FE972DBA6");

                    b.HasIndex("HandledBy");

                    b.HasIndex("ReportedBy");

                    b.HasIndex("SessionId");

                    b.HasIndex(new[] { "Status", "CreatedAt" }, "idx_incidents_open")
                        .HasFilter("([status] IN ('open', 'in_progress'))");

                    b.ToTable("incidents", (string)null);
                });

            modelBuilder.Entity("ParkingBuildingManagementSystem_BE.Models.ParkingSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ActualCheckin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("actual_checkin")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("ActualCheckout")
                        .HasColumnType("datetime2")
                        .HasColumnName("actual_checkout");

                    b.Property<decimal>("AppliedPricePerHour")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("applied_price_per_hour");

                    b.Property<int?>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("booking_id");

                    b.Property<string>("CheckinFaceImg")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("checkin_face_img");

                    b.Property<string>("CheckinVehicleImg")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("checkin_vehicle_img");

                    b.Property<string>("CheckoutFaceImg")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("checkout_face_img");

                    b.Property<string>("CheckoutVehicleImg")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("checkout_vehicle_img");

                    b.Property<string>("EntryGate")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("entry_gate");

                    b.Property<int>("FloorId")
                        .HasColumnType("int")
                        .HasColumnName("floor_id");

                    b.Property<string>("LicensePlateSnapshot")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("license_plate_snapshot");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("notes");

                    b.Property<string>("SessionType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("walkin")
                        .HasColumnName("session_type");

                    b.Property<int>("StaffCheckinId")
                        .HasColumnType("int")
                        .HasColumnName("staff_checkin_id");

                    b.Property<int?>("StaffCheckoutId")
                        .HasColumnType("int")
                        .HasColumnName("staff_checkout_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("active")
                        .HasColumnName("status");

                    b.Property<int?>("VehicleId")
                        .HasColumnType("int")
                        .HasColumnName("vehicle_id");

                    b.Property<int>("VehicleTypeId")
                        .HasColumnType("int")
                        .HasColumnName("vehicle_type_id");

                    b.HasKey("Id")
                        .HasName("PK__parking___3213E83F2153E77F");

                    b.HasIndex("StaffCheckinId");

                    b.HasIndex("StaffCheckoutId");

                    b.HasIndex("VehicleTypeId");

                    b.HasIndex(new[] { "FloorId", "Status" }, "idx_sessions_floor_active")
                        .HasFilter("([status]='active')");

                    b.HasIndex(new[] { "LicensePlateSnapshot", "Status" }, "idx_sessions_plate");

                    b.HasIndex(new[] { "FloorId", "VehicleTypeId", "ActualCheckin", "ActualCheckout" }, "idx_sessions_report");

                    b.HasIndex(new[] { "VehicleId", "ActualCheckin" }, "idx_sessions_vehicle")
                        .IsDescending(false, true)
                        .HasFilter("([vehicle_id] IS NOT NULL)");

                    b.HasIndex(new[] { "LicensePlateSnapshot" }, "uq_active_session_plate")
                        .IsUnique()
                        .HasFilter("([status]='active')");

                    b.HasIndex(new[] { "VehicleId" }, "uq_active_session_vehicle")
                        .IsUnique()
                        .HasFilter("([status]='active' AND [vehicle_id] IS NOT NULL)");

                    b.HasIndex(new[] { "BookingId" }, "uq_session_per_booking")
                        .IsUnique()
                        .HasFilter("([booking_id] IS NOT NULL)");

                    b.ToTable("parking_sessions", (string)null);
                });

            modelBuilder.Entity("ParkingBuildingManagementSystem_BE.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("amount");

                    b.Property<int?>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("booking_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("paid_at");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("cash")
                        .HasColumnName("payment_method");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("payment_type");

                    b.Property<int?>("SessionId")
                        .HasColumnType("int")
                        .HasColumnName("session_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.Property<string>("TransactionRef")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("transaction_ref");

                    b.Property<int?>("ViolationId")
                        .HasColumnType("int")
                        .HasColumnName("violation_id");

                    b.HasKey("Id")
                        .HasName("PK__payments__3213E83FCFC56C14");

                    b.HasIndex("ViolationId");

                    b.HasIndex(new[] { "BookingId", "Status" }, "idx_payments_booking");

                    b.HasIndex(new[] { "Status", "PaidAt", "PaymentType" }, "idx_payments_revenue")
                        .HasFilter("([status]='completed')");

                    b.HasIndex(new[] { "SessionId", "PaymentType", "Status" }, "idx_payments_session");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("ParkingBuildingManagementSystem_BE.Models.Policy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("PolicyType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("policy_type");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("PK__policies__3213E83F25269192");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("policies", (string)null);
                });

            modelBuilder.Entity("ParkingBuildingManagementSystem_BE.Models.PricingPolicy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<decimal>("DepositAmount")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("deposit_amount");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("effective_from");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date")
                        .HasColumnName("effective_to");

                    b.Property<int?>("FloorId")
                        .HasColumnType("int")
                        .HasColumnName("floor_id");

                    b.Property<decimal>("PricePerHour")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("price_per_hour");

                    b.Property<int>("VehicleTypeId")
                        .HasColumnType("int")
                        .HasColumnName("vehicle_type_id");

                    b.HasKey("Id")
                        .HasName("PK__pricing___3213E83FDF3B755A");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("FloorId");

                    b.HasIndex("VehicleTypeId");

                    b.ToTable("pricing_policies", (string)null);
                });

            modelBuilder.Entity("ParkingBuildingManagementSystem_BE.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("ManagerReply")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("manager_reply");

                    b.Property<byte>("Rating")
                        .HasColumnType("tinyint")
                        .HasColumnName("rating");

                    b.Property<DateTime?>("RepliedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("replied_at");

                    b.Property<int?>("RepliedBy")
                        .HasColumnType("int")
                        .HasColumnName("replied_by");

                    b.Property<int>("SessionId")
                        .HasColumnType("int")
                        .HasColumnName("session_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK__reviews__3213E83F306D2C90");

                    b.HasIndex("RepliedBy");

                    b.HasIndex("SessionId");

                    b.HasIndex(new[] { "UserId", "SessionId" }, "uq_review_per_session")
                        .IsUnique();

                    b.ToTable("reviews", (string)null);
                });

            modelBuilder.Entity("ParkingBuildingManagementSystem_BE.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("PK__users__3213E83FFA080EC5");

                    b.HasIndex(new[] { "Email" }, "UQ__users__AB6E6164D9C2C462")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ParkingBuildingManagementSystem_BE.Models.VFloorAvailability", b =>
                {
                    b.Property<int?>("AvailableCount")
                        .HasColumnType("int")
                        .HasColumnName("available_count");

                    b.Property<int>("FloorId")
                        .HasColumnType("int")
                        .HasColumnName("floor_id");

                    b.Property<string>("FloorName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("floor_name");

                    b.Property<int?>("OccupiedCount")
                        .HasColumnType("int")
                        .HasColumnName("occupied_count");

                    b.Property<int?>("ReservedCount")
                        .HasColumnType("int")
                        .HasColumnName("reserved_count");

                    b.Property<int>("TotalSlots")
                        .HasColumnType("int")
                        .HasColumnName("total_slots");

                    b.ToTable((string)null);

                    b.ToView("v_floor_availability", (string)null);
                });

            modelBuilder.Entity("ParkingBuildingManagementSystem_BE.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("license_plate");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<int>("VehicleTypeId")
                        .HasColumnType("int")
                        .HasColumnName("vehicle_type_id");

                    b.HasKey("Id")
                        .HasName("PK__vehicles__3213E83FA00C3C32");

                    b.HasIndex("UserId");

                    b.HasIndex("VehicleTypeId");

                    b.HasIndex(new[] { "LicensePlate" }, "UQ__vehicles__F72CD56E063A8FF0")
                        .IsUnique();

                    b.ToTable("vehicles", (string)null);
                });

            modelBuilder.Entity("ParkingBuildingManagementSystem_BE.Models.VehicleType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK__vehicle___3213E83FD65AFB26");

                    b.HasIndex(new[] { "Name" }, "UQ__vehicle___72E12F1B89295807")
                        .IsUnique();

                    b.ToTable("vehicle_types", (string)null);
                });

            modelBuilder.Entity("ParkingBuildingManagementSystem_BE.Models.Violation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<decimal>("FineAmount")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("fine_amount");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit")
                        .HasColumnName("is_paid");

                    b.Property<DateTime>("RecordedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("recorded_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("RecordedBy")
                        .HasColumnType("int")
                        .HasColumnName("recorded_by");

                    b.Property<int>("SessionId")
                        .HasColumnType("int")
                        .HasColumnName("session_id");

                    b.Property<string>("ViolationType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("violation_type");

                    b.HasKey("Id")
                        .HasName("PK__violatio__3213E83F712F549B");

                    b.HasIndex("RecordedBy");

                    b.HasIndex(new[] { "SessionId", "IsPaid" }, "idx_violations_unpaid")
                        .HasFilter("([is_paid]=(0))");

                    b.ToTable("violations", (string)null);
                });

            modelBuilder.Entity("FloorVehicleType", b =>
                {
                    b.HasOne("ParkingBuildingManagementSystem_BE.Models.Floor", null)
                        .WithMany()
                        .HasForeignKey("FloorId")
                        .IsRequired()
                        .HasConstraintName("fk_fvt_floor");

                    b.HasOne("ParkingBuildingManagementSystem_BE.Models.VehicleType", null)
                        .WithMany()
                        .HasForeignKey("VehicleTypeId")
                        .IsRequired()
                        .HasConstraintName("fk_fvt_type");
                });

            modelBuilder.Entity("ParkingBuildingManagementSystem_BE.Models.ActivityLog", b =>
                {
                    b.HasOne("ParkingBuildingManagementSystem_BE.Models.User", "User")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("fk_logs_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ParkingBuildingManagementSystem_BE.Models.Booking", b =>
                {
                    b.HasOne("ParkingBuildingManagementSystem_BE.Models.Floor", "Floor")
                        .WithMany("Bookings")
                        .HasForeignKey("FloorId")
                        .IsRequired()
                        .HasConstraintName("fk_bookings_floor");

                    b.HasOne("ParkingBuildingManagementSystem_BE.Models.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("fk_bookings_user");

                    b.HasOne("ParkingBuildingManagementSystem_BE.Models.Vehicle", "Vehicle")
                        .WithMany("Bookings")
                        .HasForeignKey("VehicleId")
                        .IsRequired()
                        .HasConstraintName("fk_bookings_vehicle");

                    b.HasOne("ParkingBuildingManagementSystem_BE.Models.VehicleType", "VehicleType")
                        .WithMany("Bookings")
                        .HasForeignKey("VehicleTypeId")
                        .IsRequired()
                        .HasConstraintName("fk_bookings_vtype");

                    b.Navigation("Floor");

                    b.Navigation("User");

                    b.Navigation("Vehicle");

                    b.Navigation("VehicleType");
                });

            modelBuilder.Entity("ParkingBuildingManagementSystem_BE.Models.Incident", b =>
                {
                    b.HasOne("ParkingBuildingManagementSystem_BE.Models.User", "HandledByNavigation")
                        .WithMany("IncidentHandledByNavigations")
                        .HasForeignKey("HandledBy")
                        .HasConstraintName("fk_incidents_handler");

                    b.HasOne("ParkingBuildingManagementSystem_BE.Models.User", "ReportedByNavigation")
                        .WithMany("IncidentReportedByNavigations")
                        .HasForeignKey("ReportedBy")
                        .IsRequired()
                        .HasConstraintName("fk_incidents_reporter");

                    b.HasOne("ParkingBuildingManagementSystem_BE.Models.ParkingSession", "Session")
                        .WithMany("Incidents")
                        .HasForeignKey("SessionId")
                        .HasConstraintName("fk_incidents_session");

                    b.Navigation("HandledByNavigation");

                    b.Navigation("ReportedByNavigation");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("ParkingBuildingManagementSystem_BE.Models.ParkingSession", b =>
                {
                    b.HasOne("ParkingBuildingManagementSystem_BE.Models.Booking", "Booking")
                        .WithOne("ParkingSession")
                        .HasForeignKey("ParkingBuildingManagementSystem_BE.Models.ParkingSession", "BookingId")
                        .HasConstraintName("fk_session_booking");

                    b.HasOne("ParkingBuildingManagementSystem_BE.Models.Floor", "Floor")
                        .WithMany("ParkingSessions")
                        .HasForeignKey("FloorId")
                        .IsRequired()
                        .HasConstraintName("fk_session_floor");

                    b.HasOne("ParkingBuildingManagementSystem_BE.Models.User", "StaffCheckin")
                        .WithMany("ParkingSessionStaffCheckins")
                        .HasForeignKey("StaffCheckinId")
                        .IsRequired()
                        .HasConstraintName("fk_session_staff_in");

                    b.HasOne("ParkingBuildingManagementSystem_BE.Models.User", "StaffCheckout")
                        .WithMany("ParkingSessionStaffCheckouts")
                        .HasForeignKey("StaffCheckoutId")
                        .HasConstraintName("fk_session_staff_out");

                    b.HasOne("ParkingBuildingManagementSystem_BE.Models.Vehicle", "Vehicle")
                        .WithOne("ParkingSession")
                        .HasForeignKey("ParkingBuildingManagementSystem_BE.Models.ParkingSession", "VehicleId")
                        .HasConstraintName("fk_session_vehicle");

                    b.HasOne("ParkingBuildingManagementSystem_BE.Models.VehicleType", "VehicleType")
                        .WithMany("ParkingSessions")
                        .HasForeignKey("VehicleTypeId")
                        .IsRequired()
                        .HasConstraintName("fk_session_vtype");

                    b.Navigation("Booking");

                    b.Navigation("Floor");

                    b.Navigation("StaffCheckin");

                    b.Navigation("StaffCheckout");

                    b.Navigation("Vehicle");

                    b.Navigation("VehicleType");
                });

            modelBuilder.Entity("ParkingBuildingManagementSystem_BE.Models.Payment", b =>
                {
                    b.HasOne("ParkingBuildingManagementSystem_BE.Models.Booking", "Booking")
                        .WithMany("Payments")
                        .HasForeignKey("BookingId")
                        .HasConstraintName("fk_payments_booking");

                    b.HasOne("ParkingBuildingManagementSystem_BE.Models.ParkingSession", "Session")
                        .WithMany("Payments")
                        .HasForeignKey("SessionId")
                        .HasConstraintName("fk_payments_session");

                    b.HasOne("ParkingBuildingManagementSystem_BE.Models.Violation", "Violation")
                        .WithMany("Payments")
                        .HasForeignKey("ViolationId")
                        .HasConstraintName("fk_payments_violation");

                    b.Navigation("Booking");

                    b.Navigation("Session");

                    b.Navigation("Violation");
                });

            modelBuilder.Entity("ParkingBuildingManagementSystem_BE.Models.Policy", b =>
                {
                    b.HasOne("ParkingBuildingManagementSystem_BE.Models.User", "UpdatedByNavigation")
                        .WithMany("Policies")
                        .HasForeignKey("UpdatedBy")
                        .HasConstraintName("fk_policies_updater");

                    b.Navigation("UpdatedByNavigation");
                });

            modelBuilder.Entity("ParkingBuildingManagementSystem_BE.Models.PricingPolicy", b =>
                {
                    b.HasOne("ParkingBuildingManagementSystem_BE.Models.User", "CreatedByNavigation")
                        .WithMany("PricingPolicies")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("fk_pricing_creator");

                    b.HasOne("ParkingBuildingManagementSystem_BE.Models.Floor", "Floor")
                        .WithMany("PricingPolicies")
                        .HasForeignKey("FloorId")
                        .HasConstraintName("fk_pricing_floor");

                    b.HasOne("ParkingBuildingManagementSystem_BE.Models.VehicleType", "VehicleType")
                        .WithMany("PricingPolicies")
                        .HasForeignKey("VehicleTypeId")
                        .IsRequired()
                        .HasConstraintName("fk_pricing_type");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Floor");

                    b.Navigation("VehicleType");
                });

            modelBuilder.Entity("ParkingBuildingManagementSystem_BE.Models.Review", b =>
                {
                    b.HasOne("ParkingBuildingManagementSystem_BE.Models.User", "RepliedByNavigation")
                        .WithMany("ReviewRepliedByNavigations")
                        .HasForeignKey("RepliedBy")
                        .HasConstraintName("fk_reviews_replier");

                    b.HasOne("ParkingBuildingManagementSystem_BE.Models.ParkingSession", "Session")
                        .WithMany("Reviews")
                        .HasForeignKey("SessionId")
                        .IsRequired()
                        .HasConstraintName("fk_reviews_session");

                    b.HasOne("ParkingBuildingManagementSystem_BE.Models.User", "User")
                        .WithMany("ReviewUsers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("fk_reviews_user");

                    b.Navigation("RepliedByNavigation");

                    b.Navigation("Session");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ParkingBuildingManagementSystem_BE.Models.Vehicle", b =>
                {
                    b.HasOne("ParkingBuildingManagementSystem_BE.Models.User", "User")
                        .WithMany("Vehicles")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("fk_vehicles_user");

                    b.HasOne("ParkingBuildingManagementSystem_BE.Models.VehicleType", "VehicleType")
                        .WithMany("Vehicles")
                        .HasForeignKey("VehicleTypeId")
                        .IsRequired()
                        .HasConstraintName("fk_vehicles_type");

                    b.Navigation("User");

                    b.Navigation("VehicleType");
                });

            modelBuilder.Entity("ParkingBuildingManagementSystem_BE.Models.Violation", b =>
                {
                    b.HasOne("ParkingBuildingManagementSystem_BE.Models.User", "RecordedByNavigation")
                        .WithMany("Violations")
                        .HasForeignKey("RecordedBy")
                        .IsRequired()
                        .HasConstraintName("fk_violations_recorder");

                    b.HasOne("ParkingBuildingManagementSystem_BE.Models.ParkingSession", "Session")
                        .WithMany("Violations")
                        .HasForeignKey("SessionId")
                        .IsRequired()
                        .HasConstraintName("fk_violations_session");

                    b.Navigation("RecordedByNavigation");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("ParkingBuildingManagementSystem_BE.Models.Booking", b =>
                {
                    b.Navigation("ParkingSession");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("ParkingBuildingManagementSystem_BE.Models.Floor", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("ParkingSessions");

                    b.Navigation("PricingPolicies");
                });

            modelBuilder.Entity("ParkingBuildingManagementSystem_BE.Models.ParkingSession", b =>
                {
                    b.Navigation("Incidents");

                    b.Navigation("Payments");

                    b.Navigation("Reviews");

                    b.Navigation("Violations");
                });

            modelBuilder.Entity("ParkingBuildingManagementSystem_BE.Models.User", b =>
                {
                    b.Navigation("ActivityLogs");

                    b.Navigation("Bookings");

                    b.Navigation("IncidentHandledByNavigations");

                    b.Navigation("IncidentReportedByNavigations");

                    b.Navigation("ParkingSessionStaffCheckins");

                    b.Navigation("ParkingSessionStaffCheckouts");

                    b.Navigation("Policies");

                    b.Navigation("PricingPolicies");

                    b.Navigation("ReviewRepliedByNavigations");

                    b.Navigation("ReviewUsers");

                    b.Navigation("Vehicles");

                    b.Navigation("Violations");
                });

            modelBuilder.Entity("ParkingBuildingManagementSystem_BE.Models.Vehicle", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("ParkingSession");
                });

            modelBuilder.Entity("ParkingBuildingManagementSystem_BE.Models.VehicleType", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("ParkingSessions");

                    b.Navigation("PricingPolicies");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("ParkingBuildingManagementSystem_BE.Models.Violation", b =>
                {
                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
